### PR TITLE
Fix media logging issue + add logging of ghost reactions

### PR DESCRIPTION
**Pull request by cloudburstwan**
This PR adds 2 features/fixes:
- Fixes a race condition regarding media logging.
- Adds detection and logging of ghost reactions.

~~_**This commit requires environment variable changes on the production host. Please do NOT merge once you have reviewed! Bilby WILL crash if these environment variables aren't set properly.**_~~

### CODE REVIEW

**Comment by sudoker0** [comment]
So, all of this is very nice progress. I just have a bit of question regarding the S3/Minio solution: So I noticed the S3 server is hardcoded as `s3.heeler.house`, and while it probably won't matter for production Bilby, how would other people (like me or Jalen) do local developing? Do we have to setup another server for storage?

**Comment by cloudburstwan** [comment]
> So, all of this is very nice progress. I just have a bit of question regarding the S3/Minio solution: So I noticed the S3 server is hardcoded as `s3.heeler.house`, and while it probably won't matter for production Bilby, how would other people (like me or Jalen) do local developing? Do we have to setup another server for storage?

I'll be providing dev credentials which just act as a 2nd way into prod, but if we need separation at any point (e.g. working on a feature which clashes with another feature using S3), I can easily duplicate another environment as Minio runs on Docker.

**Comment by cloudburstwan** [comment]
Production environment variables have been set, this PR is no longer blocked and can be merged after a review.

**Comment by sudoker0** [comment]
> > So, all of this is very nice progress. I just have a bit of question regarding the S3/Minio solution: So I noticed the S3 server is hardcoded as `s3.heeler.house`, and while it probably won't matter for production Bilby, how would other people (like me or Jalen) do local developing? Do we have to setup another server for storage?
> 
> I'll be providing dev credentials which just act as a 2nd way into prod, but if we need separation at any point (e.g. working on a feature which clashes with another feature using S3), I can easily duplicate another environment as Minio runs on Docker.

hmm alr, this i think will work for now, though i'm not exactly comfortable with this method

**Review by sudoker0 — APPROVED** [review]

**Pull request merged**
